version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm run build:prod
      - aws s3 sync dist/lodewijkwensveen s3://lodewijkwensveen --delete
      - aws s3 cp dist/lodewijkwensveen/index.html s3://lodewijkwensveen/index.html --metadata-directive REPLACE --cache-control must-revalidate,max-age=901 --content-type text/html

